### PR TITLE
Add codestyle files

### PR DESCRIPTION
**Pull request by kinggoesgaming**
add codestyle files for eclipse and intellij.

This follows the sponge style guidelines.

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
shoot i messed this one...

**Comment by Flibio** [comment]
The commit says eclipse and intellij but I just see intellij.

**Comment by kinggoesgaming** [comment]
and reflects on my previous commit

**Comment by kinggoesgaming** [comment]
closing this one as the repo link from my fork broke and can't update this PR anymore

**Comment by kinggoesgaming** [comment]
superseded by #26

**Pull request closed without merging**
