### PR TITLE
Update to SpongeAPI 4.0

### PR DESCRIPTION
**Pull request by liach**
Changes:
1. Changed `UpdatifierService` to an interface like most Sponge interfaces.
2. Added javadoc and sources jar, especially for api.
3. Used minecrell's licenser instead of license plugin, more lightweight.
4. Removed constant `DEPENDENCIES` since the `@Dependency` array could not be kept in another class.

More: I've tested and it seems to work well on SpongeForge with API 4.
Edit2: Removed change 2 moving api

### CODE REVIEW

**Comment by Flibio** [comment]
On change 2 in your list, it does not appear that you moved the API anywhere.

**Comment by liach** [comment]
Um... I fixed it because originally I had a problem with javadoc task.

**Comment by Flibio** [comment]
I'all merge it when I am ready. I'm just telling you that you did not move the API package anywhere.

**Comment by liach** [comment]
Sounds good. Depends on you.

**Comment by Flibio** [comment]
I don't think the version needs to change to 2.0.0, I can't find any breaking changes.

**Comment by liach** [comment]
You can fix the version

**Pull request merged**
