### PR TITLE
Fix Project Structure

### PR DESCRIPTION
**Pull request by kinggoesgaming**
related: #13

fix the structure of the project as unconventional 
structure was used for the project.

This will break the IDE's understanding of the project
structure just set the java/main as the sources root to
fix this.

### CODE REVIEW

**Comment by Flibio** [comment]
Please see my recent comment on #13

**Comment by kinggoesgaming** [comment]
dangit... i see what when wrong :/ 

fixing now

**Comment by kinggoesgaming** [comment]
also before you merge tell me so i can rebase it

**Comment by Flibio** [comment]
Just rebase when you are done making changes.

**Comment by kinggoesgaming** [comment]
@Flibio 
This is a go from my side. Remember the IDE will get confused, as mentioned in the OP for the PR

**Comment by kinggoesgaming** [comment]
ok the api module inside the src directory wont go till we move to the new system that i discussed in #11 as gradle is stupid and doesnt want to cooperate

@Flibio you can merge it

**Comment by Flibio** [comment]
Merged into `bleeding`.

**Pull request closed without merging**
